trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    resourceGroupName: 'SneakersDeployResourceGroup'
    azureResourceManagerConnection: 'Microsoft Partner Network (30e2203a-1e9e-46db-bda9-542383d60975)'
    subscriptionId: '30e2203a-1e9e-46db-bda9-542383d60975'
    location: 'ukwest'
    templateLocation: 'Linked artifact'
    csmFile: 'template.json'
    csmParametersFile: 'parameters.json'
    deploymentMode: 'Incremental'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- script: echo Hello, world!
  displayName: 'Latest version should have run'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
